config/routes.rb
Rails.application.routes.draw do
  resources :information
  devise_for :customers
  resources :users
  get 'home/about'
  # root 'home#index'
  root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :users
end

app/models/information.rb
class Information < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :customer
    has_one :information
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  before_action :set_information, only: %i[ show edit update destroy ]

  # GET /information or /information.json
  def index
    @information = Information.all
  end

  # GET /information/1 or /information/1.json
  def show
  end

  # GET /information/new
  def new
    @information = Information.new
  end

  # GET /information/1/edit
  def edit
  end

  # POST /information or /information.json
  def create
    @information = Information.new(information_params)

    respond_to do |format|
      if @information.save
        format.html { redirect_to @information, notice: "Information was successfully created." }
        format.json { render :show, status: :created, location: @information }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /information/1 or /information/1.json
  def update
    respond_to do |format|
      if @information.update(information_params)
        format.html { redirect_to @information, notice: "Information was successfully updated." }
        format.json { render :show, status: :ok, location: @information }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /information/1 or /information/1.json
  def destroy
    @information.destroy
    respond_to do |format|
      format.html { redirect_to information_index_url, notice: "Information was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_information
      @information = Information.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def information_params
      params.require(:information).permit(:age, :gender, :country, :state, :city, :street, :zipcode, :income, :expenses, :assets, :liabilities, :dependents, :health, :activity_levels)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :authenticate_customer!, except: [:index, :show]
  before_action :correct_customer, only: [:edit, :update, :destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    #@user = User.new
    @user = current_customer.users.build
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
   # @user = User.new(user_params)
    @user = current_customer.users.build(user_params)
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_customer
    @user = current_customer.users.find_by(id: params[:id])
    redirect_to users_path, notice: "Not Authorized to edit this user" if @user.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :phone, :user_id, :customer_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Pocket Actuary', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item"> 
          <%= link_to 'About Us', home_about_path, class:"nav_link" %>
        </li>
        <% if customer_signed_in? %>
          <li class="nav-item"> 
            <%= link_to 'View Users', users_path, class:"nav_link" %>
          </li>

          <li class="nav-item"> 
            <%= link_to 'Add Users', new_user_path, class:"nav_link" %>
          </li> 
          <li class="nav-item"> 
            <%= link_to 'Sign Out', destroy_customer_session_path, method: :delete, class:"nav_link" %>
          </li>

          <li class="nav-item"> 
            <%= link_to 'Edit Profile', edit_customer_registration_path, class:"nav_link" %>
          </li>
        <% else %>
        <li class="nav-item"> 
          <%= link_to 'Sign Up', new_customer_registration_path, class:"nav_link" %>
        </li>

        <li class="nav-item"> 
          <%= link_to 'Sign In', new_customer_session_path, class:"nav_link" %>
        </li>
        <% end %>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About PocketActuary </h1>

app/views/home/index.html.erb
<h1>Pocket Actuary Home Page</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/information/_form.html.erb
<%= form_with(model: information) do |form| %>
  <% if information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(information.errors.count, "error") %> prohibited this information from being saved:</h2>

      <ul>
        <% information.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field form-group">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field form-group">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field form-group">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field form-group">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field form-group">
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>

  <div class="field form-group">
    <%= form.label :zipcode %>
    <%= form.text_field :zipcode %>
  </div>

  <div class="field form-group">
    <%= form.label :income %>
    <%= form.text_field :income %>
  </div>

  <div class="field form-group">
    <%= form.label :expenses %>
    <%= form.text_field :expenses %>
  </div>

  <div class="field form-group">
    <%= form.label :assets %>
    <%= form.text_field :assets %>
  </div>

  <div class="field form-group">
    <%= form.label :liabilities %>
    <%= form.text_field :liabilities %>
  </div>

  <div class="field form-group">
    <%= form.label :dependents %>
    <%= form.text_field :dependents %>
  </div>

  <div class="field form-group">
    <%= form.label :health %>
    <%= form.text_field :health %>
  </div>

  <div class="field form-group">
    <%= form.label :activity_levels %>
    <%= form.text_field :activity_levels %>
  </div>

  <div class="field form-group">
    <%= form.number_field :customer_id, id: :user_customer_id, class:"form-control", value:current_customer.id, type: :hidden%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/information/edit.html.erb
<h1>Editing Information</h1>

<%= render 'form', information: @information %>

<%= link_to 'Show', @information %> |
<%= link_to 'Back', information_index_path %>

app/views/information/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Information</h1>

<table>
  <thead>
    <tr>
      <th>Age</th>
      <th>Gender</th>
      <th>Country</th>
      <th>State</th>
      <th>City</th>
      <th>Street</th>
      <th>Zipcode</th>
      <th>Income</th>
      <th>Expenses</th>
      <th>Assets</th>
      <th>Liabilities</th>
      <th>Dependents</th>
      <th>Health</th>
      <th>Activity levels</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @information.each do |information| %>
      <tr>
        <td><%= information.age %></td>
        <td><%= information.gender %></td>
        <td><%= information.country %></td>
        <td><%= information.state %></td>
        <td><%= information.city %></td>
        <td><%= information.street %></td>
        <td><%= information.zipcode %></td>
        <td><%= information.income %></td>
        <td><%= information.expenses %></td>
        <td><%= information.assets %></td>
        <td><%= information.liabilities %></td>
        <td><%= information.dependents %></td>
        <td><%= information.health %></td>
        <td><%= information.activity_levels %></td>
        <td><%= link_to 'Show', information %></td>
        <td><%= link_to 'Edit', edit_information_path(information) %></td>
        <td><%= link_to 'Destroy', information, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Information', new_information_path %>

app/views/information/new.html.erb
<h1>New Information</h1>

<%= render 'form', information: @information %>

<%= link_to 'Back', information_index_path %>

app/views/information/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Age:</strong>
  <%= @information.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @information.gender %>
</p>

<p>
  <strong>Country:</strong>
  <%= @information.country %>
</p>

<p>
  <strong>State:</strong>
  <%= @information.state %>
</p>

<p>
  <strong>City:</strong>
  <%= @information.city %>
</p>

<p>
  <strong>Street:</strong>
  <%= @information.street %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @information.zipcode %>
</p>

<p>
  <strong>Income:</strong>
  <%= @information.income %>
</p>

<p>
  <strong>Expenses:</strong>
  <%= @information.expenses %>
</p>

<p>
  <strong>Assets:</strong>
  <%= @information.assets %>
</p>

<p>
  <strong>Liabilities:</strong>
  <%= @information.liabilities %>
</p>

<p>
  <strong>Dependents:</strong>
  <%= @information.dependents %>
</p>

<p>
  <strong>Health:</strong>
  <%= @information.health %>
</p>

<p>
  <strong>Activity levels:</strong>
  <%= @information.activity_levels %>
</p>

<%= link_to 'Edit', edit_information_path(@information) %> |
<%= link_to 'Back', information_index_path %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <title>PocketActuary</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header'%>
    <p class="notice"><%= notice %></p>
    <div class='container'>
     <%= yield %>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone Number"%>
  </div>

  <div class="field form-group">
    <%= form.text_field :user_id, class:"form-control", placeholder:"User Name" %>
  </div>

  <div class="field form-group">
    <%= form.number_field :customer_id, id: :user_customer_id, class:"form-control", value:current_customer.id, type: :hidden%>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<br/>
<%= render 'form', user: @user %>

<%= link_to 'Show', @user, class:"btn btn-dark"%> 
<%= link_to 'Back', users_path, class:"btn btn-dark" %>

app/views/users/index.html.erb
<% if customer_signed_in? %>
<p id="notice"><%= notice %></p>

<h1>Pocket Actuary Users</h1>
<br/>
<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>User</th>
      <th colspan="2"></th>
    </tr>
 </thead>

  <tbody>
    <% @users.each do |user| %>
      <% if user.customer == current_customer%>
        <tr>
          <td><%= link_to user.first_name + ' '+ user.last_name, user %></td>
          <td><%= user.email %></td>
          <td><%= user.phone %></td>
          <td><%= user.user_id %></td>
          <td><%= link_to 'Add Info', new_information_path, class:'btn btn-outline-success btn-sm'%></td>
          <td><%= link_to 'Edit', edit_user_path(user), class:'btn btn-outline-info btn-sm'%></td>
          <td><%= link_to 'Delete', user, class:'btn btn-outline-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class:"btn btn-dark" %>

<% else %>
<h1>Pocket Actuary Home Page</h1>
<p>Find me in app/views/home/index.html.erb</p>

<% end %>

app/views/users/new.html.erb
<h1>Add a New User</h1>
<br/>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card" style="width: 20rem; height: 20rem;">
  <div class="card-body" style="background-image: url('https://wallpaperaccess.com/full/449895.jpg');">
    <h5 class="card-title"><%= @user.first_name %> <%= @user.last_name %></h5>
    <p class="card-text"> <%= @user.email %> | <%= @user.phone %> | <%= @user.user_id %></p>
    <br/><br/><br/><br/>
     <%= link_to 'See Stats', information_path(@user), class:"btn btn-success" %>
    <%= link_to 'Edit', edit_user_path(@user), class:"btn btn-dark" %> 
    <%= link_to 'Back', users_path, class:"btn btn-dark" %>
  </div>
</div>